create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  pathway text not null check (pathway in ('PARTICIPANT', 'OBSERVER')),
  name text not null,
  email text not null,
  mobile text not null,
  telegram_username text,
  role text not null,
  mun_experience text not null check (mun_experience in ('Yes', 'No')),
  mun_experience_details text,
  debate_experience text not null check (debate_experience in ('Yes', 'No')),
  debate_experience_details text,
  icj_experience text not null check (icj_experience in ('Yes', 'No')),
  icj_experience_details text,
  created_at timestamptz not null default now()
);

create index if not exists registrations_created_at_idx
  on public.registrations (created_at desc);

create index if not exists registrations_email_idx
  on public.registrations (lower(email));

alter table public.registrations enable row level security;

-- No public RLS policies are created intentionally.
-- The Vercel API uses the Supabase service-role key server-side.
